theme = "doom_acario_dark"

[editor]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[editor.cursor-shape]
insert="bar"

[editor.file-picker]
hidden = false

[keys.normal]
A-F = ":format"
A-c = ":buffer-close"
A-C = ":buffer-close!"
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
C-r = ":reload"
A-R = ":reload-all"
W = ":w!"

[keys.insert]
C-left = "move_prev_word_start"
C-right = "move_next_word_end"

